name: release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: actions/checkout@v3

      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-10-aarch64-linux-gnu
          
          cd web
          npm install
          npm run build
          cd ..

          go mod tidy
          go get github.com/jessevdk/go-assets-builder
          go install github.com/jessevdk/go-assets-builder@latest
          make release

      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          files: "opsw-*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
